In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# Theories

#### Inventory level: The current amount of a product that a business has in stock. 
#### Lead time ( transit time ):  Transit time is defined as the time required delivering the product to its ship-to location.
####

In [11]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split   
import math

In [12]:
data = pd.read_csv("../dataset/training_set.csv")

print("Shape of data: ", data.shape)

data

Shape of data:  (1687860, 23)

,sku,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,...,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop,went_on_backorder
0,1026827,0,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,No,No,No,Yes,No,No
1,1043384,2,9.0,0,0,0,0,0,0,0,...,0,0.99,0.99,0,No,No,No,Yes,No,No
2,1043696,2,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,Yes,No,No,Yes,No,No
3,1043852,7,8.0,0,0,0,0,0,0,0,...,0,0.10,0.13,0,No,No,No,Yes,No,No
4,1044048,8,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,Yes,No,No,Yes,No,No
5,1044198,13,8.0,0,0,0,0,0,0,0,...,0,0.82,0.87,0,No,No,No,Yes,No,No
6,1044643,1095,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,Yes,No,No,Yes,No,No
7,1045098,6,2.0,0,0,0,0,0,0,0,...,0,0.00,0.00,0,Yes,No,Yes,Yes,No,No
8,1045815,140,NaN,0,15,114,152,0,0,0,...,0,-99.00,-99.00,0,No,No,No,Yes,No,No
9,1045867,4,8.0,0,0,0,0,0,0,0,...,0,0.82,0.87,0,No,No,No,Yes,No,No
10,1045918,0,2.0,0,0,0,0,0,0,0,...,0,0.91,0.82,0,No,No,No,Yes,No,No
11,1047146,20,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,Yes,No,No,Yes,No,No
12,1047199,18,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,Yes,No,No,Yes,No,No
13,1047661,29,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,Yes,No,No,No,No,No
14,1049160,10,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,Yes,No,No,Yes,No,No
15,1049468,11,8.0,0,0,0,0,0,0,0,...,0,0.82,0.78,0,No,No,No,Yes,No,No
16,1050390,12,2.0,0,0,0,0,0,0,0,...,0,1.00,0.98,0,No,No,No,Yes,No,No
17,1050440,169,2.0,0,0,0,0,0,0,0,...,0,1.00,1.00,0,No,No,No,Yes,No,No
18,1117808,4,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,No,No,No,Yes,No,No
19,1050856,147,8.0,0,0,0,0,0,0,0,...,0,-99.00,1.00,0,No,No,Yes,Yes,No,No
20,1118063,8,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,Yes,No,No,Yes,No,No
21,1127154,18,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,Yes,No,No,Yes,No,No
22,1127410,9,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,Yes,No,No,Yes,No,No
23,1128393,33,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,Yes,No,Yes,Yes,No,No
24,1051516,82,8.0,0,0,0,0,0,0,0,...,0,-99.00,1.00,0,No,No,No,Yes,No,No
25,1128591,42,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,Yes,No,No,Yes,No,No
26,1130534,5,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,Yes,No,Yes,No,No,No
27,1051715,4,2.0,0,0,0,0,0,0,1,...,0,-99.00,-99.00,0,No,No,No,Yes,No,No
28,1053950,0,NaN,0,0,0,0,1,1,1,...,0,-99.00,-99.00,0,Yes,No,No,Yes,No,No
29,1132770,5,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,Yes,No,No,Yes,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1687830,1424742,517,2.0,0,874,1559,1923,200,783,1467,...,0,1.00,1.00,2,No,No,No,Yes,No,No
1687831,1411748,200,4.0,140,0,0,95,43,130,260,...,0,0.73,0.78,15,No,No,No,Yes,No,No
1687832,1420360,321,2.0,84,474,888,1284,205,568,1056,...,0,0.99,0.95,1,No,No,No,Yes,No,No
1687833,1523901,313,2.0,123,716,1496,2306,144,449,850,...,0,0.99,0.99,3,Yes,No,No,Yes,No,No
1687834,1537492,2634,3.0,1164,9060,17220,25800,2942,8329,14305,...,0,1.00,1.00,19,No,No,No,Yes,No,No
1687835,1588495,227,NaN,8,0,0,0,19,78,205,...,0,-99.00,-99.00,1,No,No,Yes,No,No,No
1687836,1473147,-94,8.0,25,786,1226,1697,304,457,731,...,0,0.44,0.62,126,No,No,No,Yes,No,Yes
1687837,1400108,2691,4.0,2479,3256,6056,9556,1073,2975,6895,...,0,0.97,0.96,1,No,No,No,Yes,No,No
1687838,1383363,-208,4.0,212,349,409,449,473,589,657,...,0,0.48,0.62,223,No,No,No,Yes,No,No
1687839,1511161,294,12.0,23,296,296,696,82,195,388,...,0,0.95,0.86,1,No,No,Yes,Yes,No,No
1687840,1547033,-47,12.0,49,249,249,249,0,180,187,...,0,0.78,0.78,47,No,No,No,Yes,No,No
1687841,1413443,688,4.0,280,690,1540,2190,314,1042,1819,...,0,0.91,0.93,10,No,No,No,Yes,No,No
1687842,1368348,25,8.0,16,135,180,255,44,98,160,...,0,0.94,0.96,16,No,No,No,Yes,No,No
1687843,1409190,-1,3.0,18,0,0,0,5,8,8,...,0,0.87,0.72,1,Yes,No,No,Yes,No,No
1687844,1529626,488,2.0,201,720,1400,2160,248,665,1265,...,0,0.93,0.96,1,No,No,No,Yes,No,No
1687845,1375433,4113,4.0,2015,2871,6200,7909,944,3388,9471,...,0,0.73,0.78,550,No,No,No,Yes,No,No
1687846,1497988,-3,12.0,0,128,179,230,97,181,296,...,0,0.00,0.01,3,No,No,No,Yes,No,No
1687847,1375861,-206,NaN,0,760,1145,1453,114,853,1764,...,0,-99.00,-99.00,206,Yes,No,No,Yes,No,No
1687848,1573563,39,8.0,5,88,119,140,17,57,113,...,0,0.69,0.69,9,No,No,No,Yes,No,No
1687849,1460296,2707,2.0,830,9000,18000,26500,2011,6998,15074,...,0,0.97,0.98,20,No,No,No,Yes,No,No
1687850,1446671,-2,NaN,0,0,62,86,6,32,46,...,0,-99.00,-99.00,32,Yes,No,No,No,No,No
1687851,1373539,-6,9.0,36,130,130,130,0,0,54,...,0,0.03,0.10,42,No,No,No,Yes,No,No
1687852,1478683,2,8.0,0,966,966,1116,47,512,1361,...,0,0.84,0.77,46,No,No,No,Yes,No,No
1687853,1489920,0,2.0,0,2071,3025,3412,4,764,764,...,0,0.98,0.99,4,No,No,No,No,No,Yes
1687854,1392420,124,8.0,140,410,780,1240,128,464,849,...,0,0.85,0.90,1,No,No,No,Yes,No,No
1687855,1407754,0,2.0,0,10,10,10,0,5,7,...,0,0.69,0.69,5,Yes,No,No,Yes,No,No
1687856,1373987,-1,NaN,0,5,7,9,1,3,3,...,0,-99.00,-99.00,1,No,No,No,Yes,No,No
1687857,1524346,-1,9.0,0,7,9,11,0,8,11,...,0,0.86,0.84,1,Yes,No,No,No,No,Yes
1687858,1439563,62,9.0,16,39,87,126,35,63,153,...,0,0.86,0.84,6,No,No,No,Yes,No,No
1687859,1502009,19,4.0,0,0,0,0,2,7,12,...,0,0.73,0.78,1,No,No,No,Yes,No,No

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1687860 entries, 0 to 1687859
Data columns (total 23 columns):
sku                  1687860 non-null int64
national_inv         1687860 non-null int64
lead_time            1586967 non-null float64
in_transit_qty       1687860 non-null int64
forecast_3_month     1687860 non-null int64
forecast_6_month     1687860 non-null int64
forecast_9_month     1687860 non-null int64
sales_1_month        1687860 non-null int64
sales_3_month        1687860 non-null int64
sales_6_month        1687860 non-null int64
sales_9_month        1687860 non-null int64
min_bank             1687860 non-null int64
potential_issue      1687860 non-null object
pieces_past_due      1687860 non-null int64
perf_6_month_avg     1687860 non-null float64
perf_12_month_avg    1687860 non-null float64
local_bo_qty         1687860 non-null int64
deck_risk            1687860 non-null object
oe_constraint        1687860 non-null object
ppap_risk            1687860 non-null object
stop_auto_buy        1687860 non-null object
rev_stop             1687860 non-null object
went_on_backorder    1687860 non-null object
dtypes: float64(3), int64(13), object(7)
memory usage: 296.2+ MB

In [42]:
for i in range(len(data.columns)):
    col = data.columns[i]
    print(col)
    a = data[[col,"went_on_backorder"]][data["went_on_backorder"]=="No"][data[col]!="No"]
    b = data[[col,"went_on_backorder"]][data["went_on_backorder"]=="No"][data[col]!="Yes"]
    c = data[[col,"went_on_backorder"]][data["went_on_backorder"]=="Yes"][data[col]!="No"]
    d = data[[col,"went_on_backorder"]][data["went_on_backorder"]=="Yes"][data[col]!="Yes"]

    if len(a)<2 or len(b)<2 or len(c)<2 or len(d)<2:
        print("Match")

sku

/root/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  after removing the cwd from sys.path.
/root/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """
/root/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

/root/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  import sys

national_inv
lead_time
in_transit_qty
forecast_3_month
forecast_6_month
forecast_9_month
sales_1_month
sales_3_month
sales_6_month
sales_9_month
min_bank
potential_issue
pieces_past_due
perf_6_month_avg
perf_12_month_avg
local_bo_qty
deck_risk
oe_constraint
ppap_risk
stop_auto_buy
rev_stop
Match
went_on_backorder
Match

In [59]:
col = "rev_stop"
data[[col,"went_on_backorder"]][data["went_on_backorder"]=="Yes"][data[col]=="Yes"]

/root/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

Empty DataFrame
Columns: [rev_stop, went_on_backorder]
Index: []

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1687860 entries, 0 to 1687859
Data columns (total 23 columns):
sku                  1687860 non-null int64
national_inv         1687860 non-null int64
lead_time            1586967 non-null float64
in_transit_qty       1687860 non-null int64
forecast_3_month     1687860 non-null int64
forecast_6_month     1687860 non-null int64
forecast_9_month     1687860 non-null int64
sales_1_month        1687860 non-null int64
sales_3_month        1687860 non-null int64
sales_6_month        1687860 non-null int64
sales_9_month        1687860 non-null int64
min_bank             1687860 non-null int64
potential_issue      1687860 non-null object
pieces_past_due      1687860 non-null int64
perf_6_month_avg     1687860 non-null float64
perf_12_month_avg    1687860 non-null float64
local_bo_qty         1687860 non-null int64
deck_risk            1687860 non-null object
oe_constraint        1687860 non-null object
ppap_risk            1687860 non-null object
stop_auto_buy        1687860 non-null object
rev_stop             1687860 non-null object
went_on_backorder    1687860 non-null object
dtypes: float64(3), int64(13), object(7)
memory usage: 296.2+ MB

-------------------------------------------------------------------------

-------------------------------------------------------------------------

# Preprocessing

In [26]:
data.head(5)

,sku,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,...,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop,went_on_backorder
0,1026827,0,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,No,No,No,Yes,No,No
1,1043384,2,9.0,0,0,0,0,0,0,0,...,0,0.99,0.99,0,No,No,No,Yes,No,No
2,1043696,2,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,Yes,No,No,Yes,No,No
3,1043852,7,8.0,0,0,0,0,0,0,0,...,0,0.10,0.13,0,No,No,No,Yes,No,No
4,1044048,8,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,Yes,No,No,Yes,No,No

In [27]:
data.tail(5)

,sku,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,...,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop,went_on_backorder
1687855,1407754,0,2.0,0,10,10,10,0,5,7,...,0,0.69,0.69,5,Yes,No,No,Yes,No,No
1687856,1373987,-1,NaN,0,5,7,9,1,3,3,...,0,-99.00,-99.00,1,No,No,No,Yes,No,No
1687857,1524346,-1,9.0,0,7,9,11,0,8,11,...,0,0.86,0.84,1,Yes,No,No,No,No,Yes
1687858,1439563,62,9.0,16,39,87,126,35,63,153,...,0,0.86,0.84,6,No,No,No,Yes,No,No
1687859,1502009,19,4.0,0,0,0,0,2,7,12,...,0,0.73,0.78,1,No,No,No,Yes,No,No

####  Numberize data:
Yes = 1
No  = 0

In [28]:
data['potential_issue'] = data['potential_issue'].map({'Yes': 1, 'No': -1})
data['deck_risk'] = data['deck_risk'].map({'Yes': 1, 'No': -1})
data['oe_constraint'] = data['oe_constraint'].map({'Yes': 1, 'No': -1})
data['ppap_risk'] = data['ppap_risk'].map({'Yes': 1, 'No': -1})
data['stop_auto_buy'] = data['stop_auto_buy'].map({'Yes': 1, 'No': -1})
data['rev_stop'] = data['rev_stop'].map({'Yes': 1, 'No': -1})
data['went_on_backorder'] = data['went_on_backorder'].map({'Yes': 1, 'No': -1})

In [29]:
data.head()

,sku,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,...,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop,went_on_backorder
0,1026827,0,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,-1,-1,-1,1,-1,-1
1,1043384,2,9.0,0,0,0,0,0,0,0,...,0,0.99,0.99,0,-1,-1,-1,1,-1,-1
2,1043696,2,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,1,-1,-1,1,-1,-1
3,1043852,7,8.0,0,0,0,0,0,0,0,...,0,0.10,0.13,0,-1,-1,-1,1,-1,-1
4,1044048,8,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,1,-1,-1,1,-1,-1

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1687860 entries, 0 to 1687859
Data columns (total 23 columns):
sku                  1687860 non-null int64
national_inv         1687860 non-null int64
lead_time            1586967 non-null float64
in_transit_qty       1687860 non-null int64
forecast_3_month     1687860 non-null int64
forecast_6_month     1687860 non-null int64
forecast_9_month     1687860 non-null int64
sales_1_month        1687860 non-null int64
sales_3_month        1687860 non-null int64
sales_6_month        1687860 non-null int64
sales_9_month        1687860 non-null int64
min_bank             1687860 non-null int64
potential_issue      1687860 non-null int64
pieces_past_due      1687860 non-null int64
perf_6_month_avg     1687860 non-null float64
perf_12_month_avg    1687860 non-null float64
local_bo_qty         1687860 non-null int64
deck_risk            1687860 non-null int64
oe_constraint        1687860 non-null int64
ppap_risk            1687860 non-null int64
stop_auto_buy        1687860 non-null int64
rev_stop             1687860 non-null int64
went_on_backorder    1687860 non-null int64
dtypes: float64(3), int64(20)
memory usage: 296.2 MB

In [31]:
data

,sku,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,...,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop,went_on_backorder
0,1026827,0,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,-1,-1,-1,1,-1,-1
1,1043384,2,9.0,0,0,0,0,0,0,0,...,0,0.99,0.99,0,-1,-1,-1,1,-1,-1
2,1043696,2,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,1,-1,-1,1,-1,-1
3,1043852,7,8.0,0,0,0,0,0,0,0,...,0,0.10,0.13,0,-1,-1,-1,1,-1,-1
4,1044048,8,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,1,-1,-1,1,-1,-1
5,1044198,13,8.0,0,0,0,0,0,0,0,...,0,0.82,0.87,0,-1,-1,-1,1,-1,-1
6,1044643,1095,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,1,-1,-1,1,-1,-1
7,1045098,6,2.0,0,0,0,0,0,0,0,...,0,0.00,0.00,0,1,-1,1,1,-1,-1
8,1045815,140,NaN,0,15,114,152,0,0,0,...,0,-99.00,-99.00,0,-1,-1,-1,1,-1,-1
9,1045867,4,8.0,0,0,0,0,0,0,0,...,0,0.82,0.87,0,-1,-1,-1,1,-1,-1
10,1045918,0,2.0,0,0,0,0,0,0,0,...,0,0.91,0.82,0,-1,-1,-1,1,-1,-1
11,1047146,20,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,1,-1,-1,1,-1,-1
12,1047199,18,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,1,-1,-1,1,-1,-1
13,1047661,29,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,1,-1,-1,-1,-1,-1
14,1049160,10,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,1,-1,-1,1,-1,-1
15,1049468,11,8.0,0,0,0,0,0,0,0,...,0,0.82,0.78,0,-1,-1,-1,1,-1,-1
16,1050390,12,2.0,0,0,0,0,0,0,0,...,0,1.00,0.98,0,-1,-1,-1,1,-1,-1
17,1050440,169,2.0,0,0,0,0,0,0,0,...,0,1.00,1.00,0,-1,-1,-1,1,-1,-1
18,1117808,4,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,-1,-1,-1,1,-1,-1
19,1050856,147,8.0,0,0,0,0,0,0,0,...,0,-99.00,1.00,0,-1,-1,1,1,-1,-1
20,1118063,8,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,1,-1,-1,1,-1,-1
21,1127154,18,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,1,-1,-1,1,-1,-1
22,1127410,9,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,1,-1,-1,1,-1,-1
23,1128393,33,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,1,-1,1,1,-1,-1
24,1051516,82,8.0,0,0,0,0,0,0,0,...,0,-99.00,1.00,0,-1,-1,-1,1,-1,-1
25,1128591,42,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,1,-1,-1,1,-1,-1
26,1130534,5,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,1,-1,1,-1,-1,-1
27,1051715,4,2.0,0,0,0,0,0,0,1,...,0,-99.00,-99.00,0,-1,-1,-1,1,-1,-1
28,1053950,0,NaN,0,0,0,0,1,1,1,...,0,-99.00,-99.00,0,1,-1,-1,1,-1,-1
29,1132770,5,NaN,0,0,0,0,0,0,0,...,0,-99.00,-99.00,0,1,-1,-1,1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1687830,1424742,517,2.0,0,874,1559,1923,200,783,1467,...,0,1.00,1.00,2,-1,-1,-1,1,-1,-1
1687831,1411748,200,4.0,140,0,0,95,43,130,260,...,0,0.73,0.78,15,-1,-1,-1,1,-1,-1
1687832,1420360,321,2.0,84,474,888,1284,205,568,1056,...,0,0.99,0.95,1,-1,-1,-1,1,-1,-1
1687833,1523901,313,2.0,123,716,1496,2306,144,449,850,...,0,0.99,0.99,3,1,-1,-1,1,-1,-1
1687834,1537492,2634,3.0,1164,9060,17220,25800,2942,8329,14305,...,0,1.00,1.00,19,-1,-1,-1,1,-1,-1
1687835,1588495,227,NaN,8,0,0,0,19,78,205,...,0,-99.00,-99.00,1,-1,-1,1,-1,-1,-1
1687836,1473147,-94,8.0,25,786,1226,1697,304,457,731,...,0,0.44,0.62,126,-1,-1,-1,1,-1,1
1687837,1400108,2691,4.0,2479,3256,6056,9556,1073,2975,6895,...,0,0.97,0.96,1,-1,-1,-1,1,-1,-1
1687838,1383363,-208,4.0,212,349,409,449,473,589,657,...,0,0.48,0.62,223,-1,-1,-1,1,-1,-1
1687839,1511161,294,12.0,23,296,296,696,82,195,388,...,0,0.95,0.86,1,-1,-1,1,1,-1,-1
1687840,1547033,-47,12.0,49,249,249,249,0,180,187,...,0,0.78,0.78,47,-1,-1,-1,1,-1,-1
1687841,1413443,688,4.0,280,690,1540,2190,314,1042,1819,...,0,0.91,0.93,10,-1,-1,-1,1,-1,-1
1687842,1368348,25,8.0,16,135,180,255,44,98,160,...,0,0.94,0.96,16,-1,-1,-1,1,-1,-1
1687843,1409190,-1,3.0,18,0,0,0,5,8,8,...,0,0.87,0.72,1,1,-1,-1,1,-1,-1
1687844,1529626,488,2.0,201,720,1400,2160,248,665,1265,...,0,0.93,0.96,1,-1,-1,-1,1,-1,-1
1687845,1375433,4113,4.0,2015,2871,6200,7909,944,3388,9471,...,0,0.73,0.78,550,-1,-1,-1,1,-1,-1
1687846,1497988,-3,12.0,0,128,179,230,97,181,296,...,0,0.00,0.01,3,-1,-1,-1,1,-1,-1
1687847,1375861,-206,NaN,0,760,1145,1453,114,853,1764,...,0,-99.00,-99.00,206,1,-1,-1,1,-1,-1
1687848,1573563,39,8.0,5,88,119,140,17,57,113,...,0,0.69,0.69,9,-1,-1,-1,1,-1,-1
1687849,1460296,2707,2.0,830,9000,18000,26500,2011,6998,15074,...,0,0.97,0.98,20,-1,-1,-1,1,-1,-1
1687850,1446671,-2,NaN,0,0,62,86,6,32,46,...,0,-99.00,-99.00,32,1,-1,-1,-1,-1,-1
1687851,1373539,-6,9.0,36,130,130,130,0,0,54,...,0,0.03,0.10,42,-1,-1,-1,1,-1,-1
1687852,1478683,2,8.0,0,966,966,1116,47,512,1361,...,0,0.84,0.77,46,-1,-1,-1,1,-1,-1
1687853,1489920,0,2.0,0,2071,3025,3412,4,764,764,...,0,0.98,0.99,4,-1,-1,-1,-1,-1,1
1687854,1392420,124,8.0,140,410,780,1240,128,464,849,...,0,0.85,0.90,1,-1,-1,-1,1,-1,-1
1687855,1407754,0,2.0,0,10,10,10,0,5,7,...,0,0.69,0.69,5,1,-1,-1,1,-1,-1
1687856,1373987,-1,NaN,0,5,7,9,1,3,3,...,0,-99.00,-99.00,1,-1,-1,-1,1,-1,-1
1687857,1524346,-1,9.0,0,7,9,11,0,8,11,...,0,0.86,0.84,1,1,-1,-1,-1,-1,1
1687858,1439563,62,9.0,16,39,87,126,35,63,153,...,0,0.86,0.84,6,-1,-1,-1,1,-1,-1
1687859,1502009,19,4.0,0,0,0,0,2,7,12,...,0,0.73,0.78,1,-1,-1,-1,1,-1,-1

In [32]:
data.isnull().sum()

sku                       0
national_inv              0
lead_time            100893
in_transit_qty            0
forecast_3_month          0
forecast_6_month          0
forecast_9_month          0
sales_1_month             0
sales_3_month             0
sales_6_month             0
sales_9_month             0
min_bank                  0
potential_issue           0
pieces_past_due           0
perf_6_month_avg          0
perf_12_month_avg         0
local_bo_qty              0
deck_risk                 0
oe_constraint             0
ppap_risk                 0
stop_auto_buy             0
rev_stop                  0
went_on_backorder         0
dtype: int64

In [33]:
data.describe()

,sku,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,...,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop,went_on_backorder
count,1.687860e+06,1.687860e+06,1.586967e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,...,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06
mean,2.094460e+06,4.961118e+02,7.872267e+00,4.405202e+01,1.781193e+02,3.449867e+02,5.063644e+02,5.592607e+01,1.750259e+02,3.417288e+02,...,2.043724e+00,-6.872059e+00,-6.437947e+00,6.264507e-01,-5.408588e-01,-9.997097e-01,-7.584705e-01,9.276172e-01,-9.991338e-01,-9.866186e-01
std,6.730819e+05,2.961523e+04,7.056024e+00,1.342742e+03,5.026553e+03,9.795152e+03,1.437892e+04,1.928196e+03,5.192378e+03,9.613167e+03,...,2.360165e+02,2.655636e+01,2.584333e+01,3.372224e+01,8.411136e-01,2.409425e-02,6.517076e-01,3.735323e-01,4.161276e-02,1.630455e-01
min,1.026827e+06,-2.725600e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,-9.900000e+01,-9.900000e+01,0.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00
25%,1.533484e+06,4.000000e+00,4.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,6.300000e-01,6.600000e-01,0.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,1.000000e+00,-1.000000e+00,-1.000000e+00
50%,1.955448e+06,1.500000e+01,8.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,2.000000e+00,...,0.000000e+00,8.200000e-01,8.100000e-01,0.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,1.000000e+00,-1.000000e+00,-1.000000e+00
75%,2.862954e+06,8.000000e+01,9.000000e+00,0.000000e+00,4.000000e+00,1.200000e+01,2.000000e+01,4.000000e+00,1.500000e+01,3.100000e+01,...,0.000000e+00,9.700000e-01,9.500000e-01,0.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,1.000000e+00,-1.000000e+00,-1.000000e+00
max,3.284919e+06,1.233440e+07,5.200000e+01,4.894080e+05,1.427612e+06,2.461360e+06,3.777304e+06,7.417740e+05,1.105478e+06,2.146625e+06,...,1.464960e+05,1.000000e+00,1.000000e+00,1.253000e+04,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00